name: train_app
description: "Your AI personal trainer"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutterflow_ui: ^0.2.0
  google_fonts: ^4.0.3
  intl: ^0.18.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/HelveticaNeueMedium.otf
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.otf
  uses-material-design: true
